src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Name should not be blank.")
     * @Assert\Length(
     *     min = 2,
     *     max = 64,
     *     minMessage = "Name must be at least {{ limit }} characters long.",
     *     maxMessage = "Name cannot be longer than {{ limit }} characters."
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Surname should not be blank.")
     * @Assert\Length(
     *      min = 2,
     *      max = 64,
     *      minMessage = "Surname must be at least {{ limit }} characters long.",
     *      maxMessage = "Surname cannot be longer than {{ limit }} characters."
     * )
     */
    private $surname;

    /**
     * @ORM\OneToMany(targetEntity=Book::class, mappedBy="author")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Title should not be blank.")
     * @Assert\Length(
     *      min = 2,
     *      max = 255,
     *      minMessage = "Title must be at least {{ limit }} characters long.",
     *      maxMessage = "Title cannot be longer than {{ limit }} characters."
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank(message="ISBN should not be blank.")
     */
    private $isbn;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Positive(message="Pages should be a positive number.")
     */
    private $pages;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="About should not be blank.")
     */
    private $about;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class, inversedBy="books", cascade={"persist"})
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): self
    {
        $this->pages = $pages;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(string $about): self
    {
        $this->about = $about;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return '/uploads/book_images/' . $this->getImage();
    }


}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class AuthorController extends AbstractController
{
    /**
     * @Route("/author", name="author_index", methods={"GET"})
     */
    public function index(Request $r): Response
    {
        $authors = $this->getDoctrine()
            ->getRepository(Author::class);

        if ($r->query->get('sort') === 'name_az') {
            $authors = $authors->findBy([], ['name' => 'asc']);
        }
        elseif ($r->query->get('sort') === 'name_za') {
            $authors = $authors->findBy([], ['name' => 'desc']);
        }
        elseif ($r->query->get('sort') === 'surname_az') {
            $authors = $authors->findBy([], ['surname' => 'asc']);
        }
        elseif ($r->query->get('sort') === 'surname_za') {
            $authors = $authors->findBy([], ['surname' => 'desc']);
        }
        else {
            $authors = $authors->findAll();
        }

        return $this->render('author/index.html.twig', [
            'authors' => $authors,
            'sortBy' => $r->query->get('sort') ?? 'default',
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'success' => $r->getSession()->getFlashBag()->get('success', [])
        ]);
    }

    /**
     * @Route("/author/create", name="author_create", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function create(Request $r): Response
    {
        return $this->render('author/create.html.twig', [
            'errors' => $r->getSession()->getFlashBag()->get('errors', [])
        ]);
    }

    /**
     * @Route("/author/store", name="author_store", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function store(Request $r, ValidatorInterface $validator): Response
    {
        $submittedToken = $r->request->get('token');
        if (!$this->isCsrfTokenValid('', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Invalid token.');
        }

        $author = new Author;
        $author->
        setName($r->request->get('author_name'))->
        setSurname($r->request->get('author_surname'));

        $errors = $validator->validate($author);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }
            return $this->redirectToRoute('author_create');
        }

        if (!$this->isCsrfTokenValid('', $submittedToken)) {
            return $this->redirectToRoute('author_create');
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($author);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', "Author {$author->getName()} {$author->getSurname()} was created.");

        return $this->redirectToRoute('author_index');
    }

    /**
     * @Route("/author/edit/{id}", name="author_edit", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $r, $id): Response
    {
        $author = $this->getDoctrine()
            ->getRepository(Author::class)
            ->find($id);

        return $this->render('author/edit.html.twig', [
            'author' => $author,
            'errors' => $r->getSession()->getFlashBag()->get('errors', [])
        ]);
    }

    /**
     * @Route("/author/update/{id}", name="author_update", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function update(Request $r, ValidatorInterface $validator, $id): Response
    {
        $submittedToken = $r->request->get('token');
        if (!$this->isCsrfTokenValid('', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Invalid token.');
        }

        $author = $this->getDoctrine()
            ->getRepository(Author::class)
            ->find($id);

        $author->
        setName($r->request->get('author_name'))->
        setSurname($r->request->get('author_surname'));


        $errors = $validator->validate($author);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }
            return $this->redirectToRoute('author_edit', ['id' => $id]);
        }
        if (!$this->isCsrfTokenValid('', $submittedToken)) {
            return $this->redirectToRoute('author_edit', ['id' => $id]);
        }


        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($author);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', "Author {$author->getName()} {$author->getSurname()} was updated.");

        return $this->redirectToRoute('author_index');
    }

    /**
     * @Route("/author/delete/{id}", name="author_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $r, $id)
    {
        $author = $this->getDoctrine()
            ->getRepository(Author::class)
            ->find($id);

        if ($author->getBooks()->count() > 0) {
            $r->getSession()->getFlashBag()->add('errors', "Can't delete: Author {$author->getName()} {$author->getSurname()} has {$author->getBooks()->count()} books.");
            return $this->redirectToRoute('author_index');
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($author);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', "Author {$author->getName()} {$author->getSurname()} was deleted.");

        return $this->redirectToRoute('author_index');
    }

    /**
     * @Route("/author/books/{id}", name="author_books", methods={"GET"})
     */
    public function authorBooks($id): Response
    {
        $author = $this->getDoctrine()
            ->getRepository(Author::class)
            ->find($id);

        $books = $author->getBooks();

        return $this->render('author/books.html.twig', [
            'books' => $books,
            'author' => $author
        ]);
    }
}

templates/author/books.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books list{% endblock %}

{% block body %}
    <h1>{{ author.name }} {{ author.surname }} Books</h1>
    <table class="table table-success table-striped">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col">Title</th>
            <th scope="col">ISBN</th>
            <th scope="col">Pages</th>
            {% if is_granted('ROLE_ADMIN') %}
                <th scope="col">Actions</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>
                    <div class="d-flex justify-content-center">
                        {% if book.image %}
                            <img src="{{ book.imagePath }}" alt="{{ book.image }}" width="100" height="100">
                        {% else %}
                            <img src="{{ asset('./build/images/noimage.jpg') }}" alt="" width="100" height="100">
                        {% endif %}
                    </div>
                </td>
                <td>{{ book.title }}</td>
                <td>{{ book.isbn }}</td>
                <td>{{ book.pages }}</td>
                {% if is_granted('ROLE_ADMIN') %}
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-outline-secondary me-2"
                               href="{{ path('book_edit', {id: book.id}) }}">Edit</a>
                            <form action="{{ path('book_delete', {id:book.id}) }}" method="POST">
                                <button type="submit" class="btn btn-outline-danger">Delete</button>
                            </form>
                        </div>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if books is empty %}
        <p class="empty">There are no books to show.</p>
    {% endif %}

{% endblock %}

templates/author/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create new Author{% endblock %}

{% block body %}
    <h1>Create new Author</h1>

    <form action="{{ path('author_store') }}" method="POST">
        <div class="row">
            <div class="col-md-6">
                <label for="author_name" class="form-label">Name</label>
                <input class="form-control" type="text" name="author_name" id="author_name">
                <label for="author_surname" class="form-label">Surname</label>
                <input class="form-control" type="text" name="author_surname" id="author_surname">
                <div class="btn-group mt-2" role="group">
                    <button type="submit" class="btn btn-outline-primary me-2">Add</button>
                    <input type="hidden" name="token" value="{{ csrf_token('') }}"/>
                    <a class="btn btn-outline-dark me-2" href="{{ path('author_index') }}">Back</a>
                </div>
            </div>
            <div class="col-md-6 mt-2">
                {% if errors is defined and errors|length > 0 %}
                    {% include 'errors/validation.html.twig' %}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
            </div>
        </div>
    </form>

{% endblock %}

templates/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Author{% endblock %}

{% block body %}
    <h1>Edit Author</h1>

    <form action="{{ path('author_update', {id:author.id}) }}" method="POST">
        <div class="row">
            <div class="col-md-6">
                <label for="author_name" class="form-label">Name</label>
                <input class="form-control" type="text" name="author_name" value="{{ author.name }}" id="author_name">
                <label for="author_surname" class="form-label">Surname</label>
                <input class="form-control" type="text" name="author_surname" value="{{ author.surname }}"
                       id="author_surname">
                <div class="btn-group mt-2" role="group">
                    <button type="submit" class="btn btn-outline-primary me-2">Save</button>
                    <input type="hidden" name="token" value="{{ csrf_token('') }}"/>
                    <a class="btn btn-outline-dark me-2" href="{{ path('author_index') }}">Back</a>
                </div>
            </div>
            <div class="col-md-6 mt-2">
                {% if errors is defined and errors|length > 0 %}
                    {% include 'errors/validation.html.twig' %}
                {% endif %}
            </div>
        </div>
    </form>

{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Authors list{% endblock %}

{% block body %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>

    <div>
        <h1>Authors</h1>
        {% if errors is defined and errors|length > 0 %}
            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                    <use xlink:href="#exclamation-triangle-fill"/>
                </svg>
                <div>
                    {% for error in errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% if success is defined and success|length > 0 %}
            <div class="alert alert-success d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
                    <use xlink:href="#check-circle-fill"/>
                </svg>
                <div>
                    {% for s in success %}
                        {{ s }}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="p-2 float-end">
            <form action="{{ path('author_index') }}" method="GET">
                <div class="input-group">
                    <span class="input-group-text" id="author_sort">List order by</span>
                    <select class="form-select" id="author_sort" name="sort">
                        <option value="default">Default</option>
                        <option value="name_az" {% if sortBy == 'name_az' %} selected {% endif %}>Name a-z</option>
                        <option value="name_za" {% if sortBy == 'name_za' %} selected {% endif %}>Name z-a</option>
                        <option value="surname_az" {% if sortBy == 'surname_az' %} selected {% endif %}>Surname a-z
                        </option>
                        <option value="surname_za" {% if sortBy == 'surname_za' %} selected {% endif %}>Surname z-a
                        </option>
                    </select>
                    <button class="btn btn-outline-dark" type="submit">Sort</button>
                </div>
            </form>
        </div>
    </div>
    <table class="table table-success table-striped">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Books list</th>
            {% if is_granted('ROLE_ADMIN') %}
            <th scope="col">Actions</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for author in authors %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ author.name }}</td>
                <td>{{ author.surname }}</td>
                <td>
                    <a class="btn btn-outline-dark me-2" href="{{ path('author_books', {id: author.id}) }}">Books</a>
                </td>
                {% if is_granted('ROLE_ADMIN') %}
                <td>
                    <div class="btn-group" role="group">
                        <a class="btn btn-outline-secondary me-2"
                           href="{{ path('author_edit', {id: author.id}) }}">Edit</a>
                        <form action="{{ path('author_delete', {id:author.id}) }}" method="POST">
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    </div>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if authors is empty %}
        <p>There are no authors to show.</p>
    {% endif %}
{% endblock %}